#!/usr/bin/env bash

set -e

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER www-data
fi

if [ -d /var/www/html/storage ]; then
    chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache 2>/dev/null || true
fi

if [ $# -gt 0 ]; then
    exec gosu www-data "$@"
else
    exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
fi
